language: generic
dist: trusty
before_install:
  - nvm install 12.14.0
  - nvm use 12.14.0

install:
  - npm install --quiet

scripts:
  - npm run-script travis_script

deploy:
  provider: pages
  github_token: $GH_TOKEN
  local_dir: ./dist/
  repo: wet-boew/cdts-sgdc-cdn
  email: $GIT_AUTHOR_EMAIL
  name: $GIT_AUTHOR_NAME
  skip_cleanup: true
  target_branch: 1.0.0-pre-alpha